version: '3'
services:
  laravel-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=chickenjoy-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=john21
    restart: always  # Enable automatic restarts
