version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always  # Enable automatic restarts
