version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chickenjoy-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: john21
    ports:
      - "5432:5432"
    restart: always  # Enable automatic restarts
